server:
  port: 7070

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TzShaka/Examen-u1-DAD.git
          searchPaths: config-data
          default-label: DAD
  security:
    user:
      name: howard
      password: teamomama
